I'm sorry, but an uncaught exception occurred.

While loading the script.
ScriptError: Name ('game/Chapter2a.rpy', 1713381467, 0) is defined twice, at game/Chapter2a.rpy:7 and game/Chapter2a.rpy:7.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/derekcampbell/Documents/Game stuffs/renpy-8.2.1-sdk/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "/Users/derekcampbell/Documents/Game stuffs/renpy-8.2.1-sdk/renpy/main.py", line 455, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "/Users/derekcampbell/Documents/Game stuffs/renpy-8.2.1-sdk/renpy/script.py", line 359, in load_script
    self.load_appropriate_file(".rpyc", [ "_ren.py", ".rpy" ], dir, fn, initcode)
  File "/Users/derekcampbell/Documents/Game stuffs/renpy-8.2.1-sdk/renpy/script.py", line 957, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=lastfn) # type: ignore
  File "/Users/derekcampbell/Documents/Game stuffs/renpy-8.2.1-sdk/renpy/script.py", line 590, in finish_load
    check_name(node)
  File "/Users/derekcampbell/Documents/Game stuffs/renpy-8.2.1-sdk/renpy/script.py", line 566, in check_name
    raise ScriptError("Name %s is defined twice, at %s:%d and %s:%d." %
ScriptError: Name ('game/Chapter2a.rpy', 1713381467, 0) is defined twice, at game/Chapter2a.rpy:7 and game/Chapter2a.rpy:7.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.2.1.24030407
 
Wed Apr 17 15:45:13 2024
